### ISSUE TITLE
Unable to ping from inside container

### ISSUE THREAD

**Issue by ocafebabe** [openSUSE/docker-containers-build#8] opened 2015-12-09 00:47 UTC
It seems that only the root user is able to ping a host from inside an openSUSE (13.2) based container:

```ssh
# docker run -i -t opensuse:13.2 /bin/bash
bash-4.2# ping -c 1 google.com
PING google.com (96.21.0.45) 56(84) bytes of data.
64 bytes from cache.google.com (96.21.0.45): icmp_seq=1 ttl=59 time=8.40 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 8.401/8.401/8.401/0.000 ms
bash-4.2# useradd test
bash-4.2# su test
bash-4.2$ ping -c 1 google.com
ping: icmp open socket: Operation not permitted
bash-4.2$ 
```

It seems that RHEL 7 is affected by this issue as well:

https://bugzilla.redhat.com/show_bug.cgi?id=1142311

So I tried to run the container with the specified switches (--cap-add net_raw --cap-add net_admin) but to no avail!

**Comment by flavio** [comment] 2016-02-01 13:27
@cyphar: could you take a look please?

**Comment by cyphar** [comment] 2016-02-01 22:29
@ocafebabe Can you please provide us with the output of the following commands?

```
% docker info
% docker version
```

**Comment by ocafebabe** [comment] 2016-02-01 22:33
There you go

```ssh
cbourque@xo-pc-cbourque:~> docker info
Containers: 0
Images: 47
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:18-393813-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.012 GB
 Data Space Total: 107.4 GB
 Data Space Available: 8.458 GB
 Metadata Space Used: 2.92 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2011-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-5.gb56b151-default
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
CPUs: 8
Total Memory: 31.37 GiB
Name: xo-pc-cbourque
ID: KCNO:2WAV:MHLO:RFX3:DN5N:ALP2:76IO:ETIV:B5IP:U76O:TW3S:S3FG
WARNING: No swap limit support
cbourque@xo-pc-cbourque:~> docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   a34a1d5
 Built:        
 OS/Arch:      linux/amd64                                                                                                                                                                                         
                                                                                                                                                                                                                   
Server:                                                                                                                                                                                                            
 Version:      1.9.1                                                                                                                                                                                               
 API version:  1.21                                                                                                                                                                                                
 Go version:   go1.5.2                                                                                                                                                                                             
 Git commit:   a34a1d5                                                                                                                                                                                             
 Built:                                                                                                                                                                                                            
 OS/Arch:      linux/amd64                                                                                                                                                                                         
cbourque@xo-pc-cbourque:~>              
```

**Comment by cyphar** [comment] 2016-02-01 22:59
@flavio I'll take a look at this today.

**Comment by cyphar** [comment] 2016-02-02 10:14
I can reproduce this issue on Arch Linux as well as openSUSE. I'll take a look at this, it looks like the capabilities are being dropped after `su` (which might be intended behaviour).

**Comment by cyphar** [comment] 2016-02-02 13:58
This is going to sound crazy, but can you verify if the following works for you:

```
% docker run -it --name testing_container opensuse:13.2 /bin/bash
# ...
```

Then, in another terminal do:

```
% docker cp $(which ping) testing_container:/usr/bin/ping
```

Then in your container do your test again. Does this "fix" the issue?

**Comment by ocafebabe** [comment] 2016-02-02 17:28
Yep now it works:

```ssh
bash-4.2# su test
bash-4.2$ ping -c 1 google.com
PING google.com (96.21.0.39) 56(84) bytes of data.
64 bytes from cache.google.com (96.21.0.39): icmp_seq=1 ttl=59 time=9.36 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.367/9.367/9.367/0.000 ms
```

But I don't think this is "intendend" behavior since it doesn't do that on Ubuntu containers...

**Comment by cyphar** [comment] 2016-02-02 21:52
@ocafebabe Yes, I think you're right that this is a bug (since your user has the capabilities, which you can confirm using `capsh --print`). I just wanted to confirm my suspicion that your problem is caused by the same issue.

**Comment by cyphar** [comment] 2016-02-03 12:36
Okay, we've root-caused this. It's because the capability extended attribute isn't set for `/usr/bin/ping`. There appears to be an issue with `kiwi` or some aspect of our build scripts. We'll investigate this further and release updated openSUSE container images.

You can install `libcap-progs` and then use `setcap cap_net_raw+ep /usr/bin/ping` as a workaround for now.

**Comment by ocafebabe** [comment] 2016-02-03 21:15
@cyphar Thanks

**Comment by cyphar** [comment] 2016-03-06 10:48
This has been fixed in kiwi. We're working on releasing new openSUSE images.

**Comment by cyphar** [comment] 2016-03-14 13:58
This has been fixed in this repo, and will be available in `library/opensuse` once docker-library/official-images#1537.

**Closed** 2016-03-14 13:58 UTC
