### ISSUE TITLE
no bash in 42.1 image

### ISSUE THREAD

**Issue by filex** [openSUSE/docker-containers-build#9] opened 2016-03-15 08:41 UTC
With the latest opensuse:42.1 image that was pushed yesterday (`b4c01597c09e`), I cannot execute bash (or anything else) anymore:

```
$ docker run -it opensuse:42.1 /bin/bash

exec: "/bin/bash": stat /bin/bash: no such file or directory
Error response from daemon: Cannot start container 4faf231a967239417003096142c756244ff3bfe3cf5bcc58459c0444bbf6bb17: [8] System error: exec: "/bin/bash": stat /bin/bash: no such file or directory
```

Using one of the opensuse:42.1 images that was up before (`ad9bc486fac9`) it works as expected:

```
$ docker run -it ad9bc486fac9 /bin/bash

bash-4.2# 
```

**Comment by flavio** [comment] 2016-03-15 10:01
This is a duplicate of https://github.com/openSUSE/docker-containers/issues/13

**Closed by flavio** 2016-03-15 10:01 UTC
